Primary changes: * In GUI mode we link against QtCore, QtGui, Qt3Support, QtOpenGL, QtNetwork, Coin, SoQt and define QT3_SUPPORT * In GUI + Debug mode we add QtTest * Now using SIM_AC_HAVE_SOQT_IFELSE and SIM_AC_HAVE_COIN_IFELSE * Initial support for generating a digital studio project file via SIM_AC_MSVC_DSP_ENABLE_OPTION
Others:

* Mangling renamed to Infixing
* Nuked MDL_HAVE_OPENGL and AX_HAVE_GL in favor of SIM_AC_HAVE_OPENGL_IFELSE
* Nuked CHECK_ZLIB in favor of SIM_AC_HAVE_ZLIB_IFELSE
* Nuked BNV_HAVE_QT
* Added SIM_AC_HAVE_LIBJPEG_IFELSE
* Initial support for generating pkg-config .pc files

TODO:
* Modify SIM_AC_HAVE_QT_IFELSE to work in our project under our different modes (right now this is happening outside the macro)
  * But keep it easy to merge in changes that Coin might make to the macro
  * This includes a sed statement to modify the Qt libraries to be Qt_debug
  * Here are the modes:
	--gui
	QtCore, QtGui, Qt3Support, QtOpenGL, QtNetwork
	Coin, SoQt
	-DQT3_SUPPORT

	--gui-debug (same as gui)
	add:QtTest

	--no gui
	QtCore, QtNetwork

	--no gui-debug (same as no-gui)
	add:QtTest
* make make force_ta work unconditionally in individual projects 
* Before release make sure to nuke extraneous autoconf macros
* Nuke ACX_PTHREAD completely in favor of SIM_AC_HAVE_PTHREAD_IFELSE
* Coin has some Debugging and Optimization macros that may be preferable to our own



Bugs:
* My initial attempt at no-gui QtCore is still present and broken

* Something wrong with pthread and recent GCC update via yum

	g++ -I/usr/local/Trolltech/Qt-4.1.0/include
	-I/usr/local/Trolltech/Qt-4.1.0/include/Qt
	-I/usr/local/Trolltech/Qt-4.1.0/include/QtOpenGL
	-I/usr/local/Trolltech/Qt-4.1.0/include/QtCore
	-I/usr/local/Trolltech/Qt-4.1.0/include/QtGui
	-I/usr/local/Trolltech/Qt-4.1.0/include/QtNetwork
	-I/usr/local/Trolltech/Qt-4.1.0/include/QtXml
	-I/usr/local/Trolltech/Qt-4.1.0/include/QtTest
	-I/usr/local/Trolltech/Qt-4.1.0/include/Qt3Support
	-I/usr/local/Trolltech/Qt-4.1.0/include/QtTest -o css_debug++
	css_debug__-main.o -L/usr/local/Trolltech/Qt-4.1.0/lib
	-L/usr/local/lib -L/usr/X11R6/lib ../ta/.libs/libta_debug.a
	./.libs/libcss_debug.a
	/home/mingus/pdp4.0/trunk/src/css/../.././src/taiqtso/.libs/libtaiqtso_debug.a
	-lreadline -ltermcap /usr/local/Trolltech/Qt-4.1.0/lib/libQtTest.so
	/usr/local/lib/libSoQt.so
	/usr/local/Trolltech/Qt-4.1.0/lib/libQtOpenGL.so -lGLU
	/usr/local/Trolltech/Qt-4.1.0/lib/libQt3Support.so
	/usr/local/Trolltech/Qt-4.1.0/lib/libQtSql.so
	/usr/local/Trolltech/Qt-4.1.0/lib/libQtXml.so
	/usr/local/Trolltech/Qt-4.1.0/lib/libQtGui.so -lpng -lXrender -lXrandr
	-lXcursor -lXinerama /usr/lib/libfreetype.so -lfontconfig
	/usr/local/Trolltech/Qt-4.1.0/lib/libQtNetwork.so
	/usr/local/Trolltech/Qt-4.1.0/lib/libQtCore.so -lz -lXmu -lXi
	/usr/local/lib/libCoin.so -lGL -lXext -lSM -lICE -lX11 -ldl -lpthread
	-lm /usr/lib/libjpeg.so -Wl,--rpath
	-Wl,/usr/local/Trolltech/Qt-4.1.0/lib -Wl,--rpath
	-Wl,/usr/local/Trolltech/Qt-4.1.0/lib
	../ta/.libs/libta_debug.a(libta_debug_la-ta_ti.o)(.text+0x36): In
	function `__gthread_once':
	/usr/lib/gcc/i386-redhat-linux/4.0.2/../../../../include/c++/4.0.2/i386-redhat-linux/bits/gthr-default.h:488:
	undefined reference to `__gthrw_pthread_once(int*, void (*)())'
	../ta/.libs/libta_debug.a(libta_debug_la-ta_ti.o)(.rodata+0x24):
	undefined reference to `__gthrw_pthread_cancel(unsigned long)'
	collect2: ld returned 1 exit status

	* Here is the reference to it

	/usr/include/c++/4.0.2/i386-redhat-linux/bits/gthr-default.h

	117: static inline int
	118: __gthread_active_p (void)
	119: {
	120:  static void *const __gthread_active_ptr
	121:    = __extension__ (void *) &__gthrw_pthread_cancel;
	122:  return __gthread_active_ptr != 0;
	123:}